development:
  cloud_name: dbji38yvs
  api_key: '343531356665815'
  api_secret: 3kfw7yqx-CMKGrSJXjjEktLVseA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dbji38yvs
  api_key: '343531356665815'
  api_secret: 3kfw7yqx-CMKGrSJXjjEktLVseA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dbji38yvs
  api_key: '343531356665815'
  api_secret: 3kfw7yqx-CMKGrSJXjjEktLVseA
  enhance_image_tag: true
static_image_support: false